import {
    HtmlIcon,
    CssIcon,
    TsIcon,
    AfterEffectsIcon,
    AppwriteIcon,
    AstroIcon,
    BoostrapIcon,
    PooIcon,
    CsharpIcon,
    FigmaIcon,
    GitIcon,
    IllustratorIcon,
    LinuxIcon,
    MicroservicesIcon,
    MvcIcon,
    NetIcon,
    PhotoshopIcon,
    PowerbiIcon,
    PremiereIcon,
    PythonIcon,
    ReactIcon,
    ReactQueryIcon,
    SpringIcon,
    SqlIcon,
    SwaggerIcon,
    TableauIcon,
    TailwindIcon,
    UnityIcon,
  } from "../../../public/assets/icons/herramientas";

export const skills= [
    { name: "HTML", icon: HtmlIcon },
    { name: "CSS", icon: CssIcon },
    { name: "TypeScript", icon: TsIcon },
    { name: "After Effects", icon: AfterEffectsIcon },
    { name: "Appwrite", icon: AppwriteIcon },
    { name: "Astro", icon: AstroIcon },
    { name: "Bootstrap", icon: BoostrapIcon },
    { name: "POO", icon: PooIcon },
    { name: "C#", icon: CsharpIcon },
    { name: "Figma", icon: FigmaIcon },
    { name: "Git", icon: GitIcon },
    { name: "Illustrator", icon: IllustratorIcon },
    { name: "Linux", icon: LinuxIcon },
    { name: "Microservices", icon: MicroservicesIcon },
    { name: "MVC", icon: MvcIcon },
    { name: ".NET", icon: NetIcon },
    { name: "Photoshop", icon: PhotoshopIcon },
    { name: "Power BI", icon: PowerbiIcon },
    { name: "Premiere", icon: PremiereIcon },
    { name: "Python", icon: PythonIcon },
    { name: "React", icon: ReactIcon },
    { name: "React Query", icon: ReactQueryIcon },
    { name: "Spring", icon: SpringIcon },
    { name: "SQL", icon: SqlIcon },
    { name: "Swagger", icon: SwaggerIcon },
    { name: "Tableau", icon: TableauIcon },
    { name: "Tailwind CSS", icon: TailwindIcon },
    { name: "Unity", icon: UnityIcon },
  ];

  